# Generated by Django 4.2.29 on 2026-09-10 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Adet')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat (TL)')),
                ('due_date', models.DateField(verbose_name='Teslim / Vade Tarihi')),
                ('defect_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kabul Edilebilir Fire Oranı (%)')),
                ('extra_terms', models.TextField(blank=True, verbose_name='Ek Şartlar / Notlar')),
                ('owner_approved', models.BooleanField(default=False, verbose_name='İlan Sahibi Onayı')),
                ('bidder_approved', models.BooleanField(default=False, verbose_name='Teklif Verenin Onayı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tam Onay Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='chat.conversation', verbose_name='Sohbet')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Fason Sözleşmesi',
                'verbose_name_plural': 'Fason Sözleşmeleri',
            },
        ),
    ]
