# Generated by Django 4.2.29 on 2026-09-07 09:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CUSTOMER', 'İlan Veren / Müşteri'), ('WORKSHOP', 'Atölye Sahibi / Üretici'), ('ADMIN', 'Yönetici')], default='CUSTOMER', max_length=20, verbose_name='Kullanıcı Rolü')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil Fotoğrafı')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TAX_CERTIFICATE', 'Vergi Levhası'), ('ID_COPY', 'Kimlik Fotokopisi'), ('OTHER', 'Diğer')], max_length=20, verbose_name='Belge Türü')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Belge Dosyası')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Firma / Atölye Adı')),
                ('tax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi Numarası (opsiyonel)')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Saha / Atölye Adresi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Firma / Atölye Açıklaması')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulanmış (Vergi Levhalı) Rozet')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profiller',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Makine Adı')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='accounts.profile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Makine',
                'verbose_name_plural': 'Makine Parkuru',
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('DENIED', 'Reddedildi')], default='PENDING', max_length=10, verbose_name='Durum')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='İstek Tarihi')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Yanıt Tarihi')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='accounts.document', verbose_name='Belge')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_document_requests', to=settings.AUTH_USER_MODEL, verbose_name='İsteği Gönderen')),
            ],
            options={
                'verbose_name': 'Belge Görüntüleme İsteği',
                'verbose_name_plural': 'Belge Görüntüleme İstekleri',
                'ordering': ['-requested_at'],
                'unique_together': {('document', 'requester')},
            },
        ),
    ]
