# Generated by Django 6.1.1 on 2026-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_defect_rate_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Ort. Sakat/Fire Memnuniyeti'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avg_payment_discipline',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Ort. Ödeme Disiplini'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avg_timeliness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Ort. Zamanında Teslimat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avg_workmanship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Ort. İşçilik Kalitesi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Değerlendirme Sayısı'),
        ),
    ]
