# Generated by Django 4.2.29 on 2026-09-09 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'İlan Kategorisi',
                'verbose_name_plural': 'İlan Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İlan Başlığı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('advert_type', models.CharField(choices=[('capacity', 'Atölye Kapasite İlanı (İş Arıyor)'), ('job', 'Fason İşi Veren İlanı (Atölye Arıyor)')], default='job', max_length=20, verbose_name='İlan Tipi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Adet / Kapasite')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=10, null=True, verbose_name='Birim Fiyat (TL)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='adverts/', verbose_name='Görsel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='fason_advert.advertcategory', verbose_name='Kategori')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL, verbose_name='İlan Sahibi')),
            ],
            options={
                'verbose_name': 'Fason İlanı',
                'verbose_name_plural': 'Fason İlanları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Teklif Mesajı')),
                ('price_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Teklif Edilen Birim Fiyat (TL)')),
                ('quantity_offer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Karşılanabilecek Adet')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('ACCEPTED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Yanıt Tarihi')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='fason_advert.advert', verbose_name='İlan')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Teklif Veren')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
                'ordering': ['-created_at'],
                'unique_together': {('advert', 'bidder')},
            },
        ),
    ]
