# Generated by Django 4.2.29 on 2026-09-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt Başlık')),
                ('content', models.TextField(verbose_name='Hakkımızda İçeriği')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='Vizyonumuz')),
                ('mission', models.TextField(blank=True, null=True, verbose_name='Misyonumuz')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Görsel')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Hakkımızda Sayfası',
                'verbose_name_plural': 'Hakkımızda Sayfası',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='İstatistik Adı (Örn: Aktif Atölye)')),
                ('value', models.CharField(max_length=50, verbose_name='Değer (Örn: 500+)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'İstatistik',
                'verbose_name_plural': 'İstatistikler',
                'ordering': ['order'],
            },
        ),
    ]
