# Generated by Django 4.2.29 on 2026-09-03 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Atölye / Firma Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Atölye Hakkında / Tanıtım')),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Çalışan / Personel Sayısı')),
                ('daily_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Günlük Üretim Kapasitesi (Adet)')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Açık Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='İletişim Telefonu')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='workshops/logos/', verbose_name='Atölye Logosu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='workshops/covers/', verbose_name='Kapak Görseli')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Onaylı Atölye mi?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Atölye',
                'verbose_name_plural': 'Atölyeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Atölye Türü (Örn: Dikim Atölyesi, Nakışhane)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Atölye Kategorisi',
                'verbose_name_plural': 'Atölye Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='WorkshopMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Makine Adı (Örn: Düz Dikiş, Reçme, Çift İğne)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='workshop.workshop', verbose_name='Atölye')),
            ],
            options={
                'verbose_name': 'Atölye Makinesi',
                'verbose_name_plural': 'Atölye Makineleri',
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='workshop.workshopcategory', verbose_name='Atölye Türü'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL, verbose_name='Atölye Sahibi'),
        ),
    ]
