# Generated by Django 4.2.29 on 2026-09-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopmachine',
            name='workshop',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='daily_capacity',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='slug',
        ),
        migrations.AddField(
            model_name='workshop',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aylık Kapasite (Parça)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Enlem (Lat)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Boylam (Lng)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='category',
            field=models.CharField(choices=[('orme', 'Örme'), ('dokuma', 'Dokuma'), ('kesim', 'Kesim / Fason Kesim'), ('utu_paket', 'Ütü & Paket'), ('baski_nakis', 'Baskı & Nakış'), ('diger', 'Diğer Fason İşler')], default='orme', max_length=50, verbose_name='Kategori / Ne Yapıyor?'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='city',
            field=models.CharField(max_length=100, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='district',
            field=models.CharField(max_length=100, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon Numarası'),
        ),
        migrations.DeleteModel(
            name='WorkshopCategory',
        ),
        migrations.DeleteModel(
            name='WorkshopMachine',
        ),
    ]
