# Generated by Django 4.2.29 on 2026-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_remove_workshopmachine_workshop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/covers/', verbose_name='Kapak Görseli'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='daily_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Günlük Üretim Kapasitesi (Adet)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Atölye Açıklaması / Uzmanlık Alanları'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta Adresi'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Çalışan Sayısı'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/logos/', verbose_name='Atölye Logosu'),
        ),
    ]
