# Generated by Django 4.2.29 on 2026-09-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Banner Başlığı')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt Başlık / Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Görseli')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Metni')),
                ('button_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Buton Linki')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='İstatistik Başlığı (Örn: Tamamlanan İşler)')),
                ('value', models.CharField(max_length=50, verbose_name='Değer (Örn: 1500+)')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='FontAwesome/Bootstrap İkon Sınıfı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'İstatistik',
                'verbose_name_plural': 'İstatistikler',
                'ordering': ['order'],
            },
        ),
    ]
