# Generated by Django 4.2.29 on 2026-09-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Şehir Adı')),
                ('code', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Plaka Kodu')),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Site Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Site Açıklaması (SEO)')),
                ('keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='Anahtar Kelimeler')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Site Logosu')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Favicon')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='Footer Telif Metni')),
            ],
            options={
                'verbose_name': 'Site Genel Ayarı',
                'verbose_name_plural': 'Site Genel Ayarları',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='İşçilik Türü')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'İşçilik / Hizmet Türü',
                'verbose_name_plural': 'İşçilik / Hizmet Türleri',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İlçe Adı')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='parameter.city', verbose_name='Şehir')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'ordering': ['name'],
            },
        ),
    ]
