# Generated by Django 4.2.29 on 2026-09-11 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workmanship_score', models.PositiveSmallIntegerField(choices=[(1, '1 - Çok Kötü'), (2, '2 - Kötü'), (3, '3 - Orta'), (4, '4 - İyi'), (5, '5 - Çok İyi')], verbose_name='İşçilik Kalitesi')),
                ('timeliness_score', models.PositiveSmallIntegerField(choices=[(1, '1 - Çok Kötü'), (2, '2 - Kötü'), (3, '3 - Orta'), (4, '4 - İyi'), (5, '5 - Çok İyi')], verbose_name='Zamanında Teslimat')),
                ('payment_discipline_score', models.PositiveSmallIntegerField(choices=[(1, '1 - Çok Kötü'), (2, '2 - Kötü'), (3, '3 - Orta'), (4, '4 - İyi'), (5, '5 - Çok İyi')], verbose_name='Ödeme Disiplini')),
                ('defect_rate_score', models.PositiveSmallIntegerField(choices=[(1, '1 - Çok Kötü'), (2, '2 - Kötü'), (3, '3 - Orta'), (4, '4 - İyi'), (5, '5 - Çok İyi')], verbose_name='Sakat/Fire Oranı Memnuniyeti')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum (opsiyonel)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contracts.contract', verbose_name='Sözleşme')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Değerlendirilen')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Değerlendiren')),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'verbose_name_plural': 'Değerlendirmeler',
                'ordering': ['-created_at'],
                'unique_together': {('contract', 'reviewer')},
            },
        ),
    ]
